var annotated_dup =
[
    [ "Board", "classBoard.html", "classBoard" ],
    [ "BoardLocations", "classBoardLocations.html", "classBoardLocations" ],
    [ "Dice", "classDice.html", "classDice" ],
    [ "DiceData", "structDiceData.html", "structDiceData" ],
    [ "GameOfUrModel", "classGameOfUrModel.html", "classGameOfUrModel" ],
    [ "GamePhaseData", "structGamePhaseData.html", "structGamePhaseData" ],
    [ "GamePieceData", "structGamePieceData.html", "structGamePieceData" ],
    [ "GameRecord", "structGameRecord.html", null ],
    [ "GameScoreData", "structGameScoreData.html", "structGameScoreData" ],
    [ "House", "classHouse.html", "classHouse" ],
    [ "HouseData", "structHouseData.html", "structHouseData" ],
    [ "MoveResultData", "structMoveResultData.html", "structMoveResultData" ],
    [ "Piece", "classPiece.html", "classPiece" ],
    [ "PieceIdentity", "structPieceIdentity.html", "structPieceIdentity" ],
    [ "PieceType", "structPieceType.html", "structPieceType" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerCPURandom", "classPlayerCPURandom.html", "classPlayerCPURandom" ],
    [ "PlayerData", "structPlayerData.html", "structPlayerData" ],
    [ "PlayerLocal", "classPlayerLocal.html", "classPlayerLocal" ],
    [ "TutorialContent", "structTutorialContent.html", null ],
    [ "UrController", "classUrController.html", "classUrController" ],
    [ "UrLookAtBoard", "classUrLookAtBoard.html", null ],
    [ "UrPieceAnimationKey", "structUrPieceAnimationKey.html", null ],
    [ "UrPlayerControls", "classUrPlayerControls.html", "classUrPlayerControls" ],
    [ "UrRecords", "classUrRecords.html", null ],
    [ "UrSceneManager", "classUrSceneManager.html", "classUrSceneManager" ],
    [ "UrSceneView", "classUrSceneView.html", null ],
    [ "UrUINavigation", "classUrUINavigation.html", null ],
    [ "UrUIRecordsBrowser", "classUrUIRecordsBrowser.html", null ],
    [ "UrUITutorialsBrowser", "classUrUITutorialsBrowser.html", null ],
    [ "UrUIVersion", "classUrUIVersion.html", null ],
    [ "UrUIView", "classUrUIView.html", null ]
];